name: Auto Empty Commit

on:
  schedule:
    - cron: "0 */10 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.PAT }}

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - run: |
          git commit --allow-empty -m "Automated empty commit: $(date -u)"
          git push origin HEAD:main
