name: Auto Empty Commit

# give the workflow permissions to write the repository contents
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */10 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true  # ensure GITHUB_TOKEN is available for push

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit and push
        run: |
          git commit --allow-empty -m "Automated empty commit: $(date -u)"
          git push origin HEAD:main
